#pragma once
enum class InputKey
{
	MOUSE_X,
	MOUSE_Y,

	MOUSE_1,
	MOUSE_2,
	MOUSE_3,
	MOUSE_4,
	MOUSE_5,
	MOUSE_6,
	MOUSE_7,
	MOUSE_8,
	MOUSE_LEFT = MOUSE_1,
	MOUSE_RIGHT = MOUSE_2,
	MOUSE_MIDDLE = MOUSE_3,

	//Keyboard
	//The numbering pulls from ASCII
	KEY_SPACE             = 32,
	KEY_APOSTROPHE        = 39,
	KEY_COMMA             = 44,
	KEY_MINUS             = 45,
	KEY_PERIOD            = 46,
	KEY_SLASH             = 47,
	KEY_0                 = 48,
	KEY_1                 = 49,
	KEY_2                 = 50,
	KEY_3                 = 51,
	KEY_4                 = 52,
	KEY_5                 = 53,
	KEY_6                 = 54,
	KEY_7                 = 55,
	KEY_8                 = 56,
	KEY_9                 = 57,
	KEY_SEMICOLON         = 59,
	KEY_EQUAL             = 61,
	KEY_A                 = 65,
	KEY_B                 = 66,
	KEY_C                 = 67,
	KEY_D                 = 68,
	KEY_E                 = 69,
	KEY_F                 = 70,
	KEY_G                 = 71,
	KEY_H                 = 72,
	KEY_I                 = 73,
	KEY_J                 = 74,
	KEY_K                 = 75,
	KEY_L                 = 76,
	KEY_M                 = 77,
	KEY_N                 = 78,
	KEY_O                 = 79,
	KEY_P                 = 80,
	KEY_Q                 = 81,
	KEY_R                 = 82,
	KEY_S                 = 83,
	KEY_T                 = 84,
	KEY_U                 = 85,
	KEY_V                 = 86,
	KEY_W                 = 87,
	KEY_X                 = 88,
	KEY_Y                 = 89,
	KEY_Z                 = 90,
	KEY_LEFT_BRACKET      = 91,
	KEY_BACKSLASH         = 92,
	KEY_RIGHT_BRACKET     = 93,
	KEY_GRAVE_ACCENT      = 96,
	KEY_WORLD_1           = 161,
	KEY_WORLD_2           = 162,

	//Gamepad Input
	//Organized like an xbox controller
	GAMEPAD_A,
	GAMEPAD_B,
	GAMEPAD_X,
	GAMEPAD_Y,
	GAMEPAD_LEFT_BUMPER,
	GAMEPAD_RIGHT_BUMPER,
	GAMEPAD_LEFT_TRIGGER,
	GAMEPAD_RIGHT_TRIGGER,
	GAMEPAD_BACK,
	GAMEPAD_START,
	GAMEPAD_GUIDE, //dont know what this is
	GAMEPAD_LEFT_THUMB,
	GAMEPAD_RIGHT_THUMB,
	GAMEPAD_DPAD_UP,
	GAMEPAD_DPAD_RIGHT,
	GAMEPAD_DPAD_DOWN,
	GAMEPAD_DPAD_LEFT,
	GAMEPAD_LEFT_STICK_X,
	GAMEPAD_LEFT_STICK_Y,
	GAMEPAD_RIGHT_STICK_X,
	GAMEPAD_RIGHT_STICK_Y
};